name: lc
favicon: null
layout_spectrum: 0.3792464684229344
typography_spectrum: 0.9552710093557835
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.46431668917648494
  lightness: 0.7665587754454464
  saturation: 0.12856699316762388
  rhythmicContrast: 0.06292002485133708
purpose: []
